#!/usr/bin/env groovy

import com.vi.Git

boolean success = true

try {
    node('docker') {
        stage('Checkout') {
            Git.mainCheckout(this)
        }

        stage('Build') {
            sh 'make build'
        }

        docker.withRegistry('https://vi-nexus.lab.vi.local/') {
            stage('Push') {
                sh 'make push'
            }
        }
    }
} catch (e) {
    echo e.toString()
    sucess = false
    currentBuild.result = 'FAILURE'
} finally {
}
